# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtty_swig
else:
    import _rtty_swig

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def high_res_timer_now():
    r"""high_res_timer_now() -> gr::high_res_timer_type"""
    return _rtty_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
    r"""high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
    return _rtty_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
    r"""high_res_timer_tps() -> gr::high_res_timer_type"""
    return _rtty_swig.high_res_timer_tps()

def high_res_timer_epoch():
    r"""high_res_timer_epoch() -> gr::high_res_timer_type"""
    return _rtty_swig.high_res_timer_epoch()
class rtty_decode_ff(object):
    r"""Proxy of C++ gr::rtty::rtty_decode_ff class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(rate, baud, polarity):
        r"""make(float rate, float baud, bool polarity) -> rtty_decode_ff_sptr"""
        return _rtty_swig.rtty_decode_ff_make(rate, baud, polarity)
    __swig_destroy__ = _rtty_swig.delete_rtty_decode_ff

# Register rtty_decode_ff in _rtty_swig:
_rtty_swig.rtty_decode_ff_swigregister(rtty_decode_ff)

def rtty_decode_ff_make(rate, baud, polarity):
    r"""rtty_decode_ff_make(float rate, float baud, bool polarity) -> rtty_decode_ff_sptr"""
    return _rtty_swig.rtty_decode_ff_make(rate, baud, polarity)

class rtty_decode_ff_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::rtty::rtty_decode_ff > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(rtty_decode_ff_sptr self) -> rtty_decode_ff_sptr
        __init__(rtty_decode_ff_sptr self, rtty_decode_ff p) -> rtty_decode_ff_sptr
        """
        _rtty_swig.rtty_decode_ff_sptr_swiginit(self, _rtty_swig.new_rtty_decode_ff_sptr(*args))

    def __deref__(self):
        r"""__deref__(rtty_decode_ff_sptr self) -> rtty_decode_ff"""
        return _rtty_swig.rtty_decode_ff_sptr___deref__(self)
    __swig_destroy__ = _rtty_swig.delete_rtty_decode_ff_sptr

    def make(self, rate, baud, polarity):
        r"""make(rtty_decode_ff_sptr self, float rate, float baud, bool polarity) -> rtty_decode_ff_sptr"""
        return _rtty_swig.rtty_decode_ff_sptr_make(self, rate, baud, polarity)

    def history(self):
        r"""history(rtty_decode_ff_sptr self) -> unsigned int"""
        return _rtty_swig.rtty_decode_ff_sptr_history(self)

    def declare_sample_delay(self, *args):
        r"""
        declare_sample_delay(rtty_decode_ff_sptr self, int which, int delay)
        declare_sample_delay(rtty_decode_ff_sptr self, unsigned int delay)
        """
        return _rtty_swig.rtty_decode_ff_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which):
        r"""sample_delay(rtty_decode_ff_sptr self, int which) -> unsigned int"""
        return _rtty_swig.rtty_decode_ff_sptr_sample_delay(self, which)

    def output_multiple(self):
        r"""output_multiple(rtty_decode_ff_sptr self) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_output_multiple(self)

    def relative_rate(self):
        r"""relative_rate(rtty_decode_ff_sptr self) -> double"""
        return _rtty_swig.rtty_decode_ff_sptr_relative_rate(self)

    def start(self):
        r"""start(rtty_decode_ff_sptr self) -> bool"""
        return _rtty_swig.rtty_decode_ff_sptr_start(self)

    def stop(self):
        r"""stop(rtty_decode_ff_sptr self) -> bool"""
        return _rtty_swig.rtty_decode_ff_sptr_stop(self)

    def nitems_read(self, which_input):
        r"""nitems_read(rtty_decode_ff_sptr self, unsigned int which_input) -> uint64_t"""
        return _rtty_swig.rtty_decode_ff_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output):
        r"""nitems_written(rtty_decode_ff_sptr self, unsigned int which_output) -> uint64_t"""
        return _rtty_swig.rtty_decode_ff_sptr_nitems_written(self, which_output)

    def max_noutput_items(self):
        r"""max_noutput_items(rtty_decode_ff_sptr self) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m):
        r"""set_max_noutput_items(rtty_decode_ff_sptr self, int m)"""
        return _rtty_swig.rtty_decode_ff_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self):
        r"""unset_max_noutput_items(rtty_decode_ff_sptr self)"""
        return _rtty_swig.rtty_decode_ff_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        r"""is_set_max_noutput_items(rtty_decode_ff_sptr self) -> bool"""
        return _rtty_swig.rtty_decode_ff_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m):
        r"""set_min_noutput_items(rtty_decode_ff_sptr self, int m)"""
        return _rtty_swig.rtty_decode_ff_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self):
        r"""min_noutput_items(rtty_decode_ff_sptr self) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_min_noutput_items(self)

    def max_output_buffer(self, i):
        r"""max_output_buffer(rtty_decode_ff_sptr self, int i) -> long"""
        return _rtty_swig.rtty_decode_ff_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args):
        r"""
        set_max_output_buffer(rtty_decode_ff_sptr self, long max_output_buffer)
        set_max_output_buffer(rtty_decode_ff_sptr self, int port, long max_output_buffer)
        """
        return _rtty_swig.rtty_decode_ff_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i):
        r"""min_output_buffer(rtty_decode_ff_sptr self, int i) -> long"""
        return _rtty_swig.rtty_decode_ff_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args):
        r"""
        set_min_output_buffer(rtty_decode_ff_sptr self, long min_output_buffer)
        set_min_output_buffer(rtty_decode_ff_sptr self, int port, long min_output_buffer)
        """
        return _rtty_swig.rtty_decode_ff_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        r"""pc_noutput_items(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        r"""pc_noutput_items_avg(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        r"""pc_noutput_items_var(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        r"""pc_nproduced(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        r"""pc_nproduced_avg(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        r"""pc_nproduced_var(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        r"""
        pc_input_buffers_full(rtty_decode_ff_sptr self, int which) -> float
        pc_input_buffers_full(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        r"""
        pc_input_buffers_full_avg(rtty_decode_ff_sptr self, int which) -> float
        pc_input_buffers_full_avg(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        r"""
        pc_input_buffers_full_var(rtty_decode_ff_sptr self, int which) -> float
        pc_input_buffers_full_var(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        r"""
        pc_output_buffers_full(rtty_decode_ff_sptr self, int which) -> float
        pc_output_buffers_full(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        r"""
        pc_output_buffers_full_avg(rtty_decode_ff_sptr self, int which) -> float
        pc_output_buffers_full_avg(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        r"""
        pc_output_buffers_full_var(rtty_decode_ff_sptr self, int which) -> float
        pc_output_buffers_full_var(rtty_decode_ff_sptr self) -> pmt_vector_float
        """
        return _rtty_swig.rtty_decode_ff_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        r"""pc_work_time(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        r"""pc_work_time_avg(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        r"""pc_work_time_var(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        r"""pc_work_time_total(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        r"""pc_throughput_avg(rtty_decode_ff_sptr self) -> float"""
        return _rtty_swig.rtty_decode_ff_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask):
        r"""set_processor_affinity(rtty_decode_ff_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _rtty_swig.rtty_decode_ff_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self):
        r"""unset_processor_affinity(rtty_decode_ff_sptr self)"""
        return _rtty_swig.rtty_decode_ff_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        r"""processor_affinity(rtty_decode_ff_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _rtty_swig.rtty_decode_ff_sptr_processor_affinity(self)

    def active_thread_priority(self):
        r"""active_thread_priority(rtty_decode_ff_sptr self) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_active_thread_priority(self)

    def thread_priority(self):
        r"""thread_priority(rtty_decode_ff_sptr self) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_thread_priority(self)

    def set_thread_priority(self, priority):
        r"""set_thread_priority(rtty_decode_ff_sptr self, int priority) -> int"""
        return _rtty_swig.rtty_decode_ff_sptr_set_thread_priority(self, priority)

    def name(self):
        r"""name(rtty_decode_ff_sptr self) -> std::string"""
        return _rtty_swig.rtty_decode_ff_sptr_name(self)

    def symbol_name(self):
        r"""symbol_name(rtty_decode_ff_sptr self) -> std::string"""
        return _rtty_swig.rtty_decode_ff_sptr_symbol_name(self)

    def input_signature(self):
        r"""input_signature(rtty_decode_ff_sptr self) -> io_signature_sptr"""
        return _rtty_swig.rtty_decode_ff_sptr_input_signature(self)

    def output_signature(self):
        r"""output_signature(rtty_decode_ff_sptr self) -> io_signature_sptr"""
        return _rtty_swig.rtty_decode_ff_sptr_output_signature(self)

    def unique_id(self):
        r"""unique_id(rtty_decode_ff_sptr self) -> long"""
        return _rtty_swig.rtty_decode_ff_sptr_unique_id(self)

    def to_basic_block(self):
        r"""to_basic_block(rtty_decode_ff_sptr self) -> basic_block_sptr"""
        return _rtty_swig.rtty_decode_ff_sptr_to_basic_block(self)

    def check_topology(self, ninputs, noutputs):
        r"""check_topology(rtty_decode_ff_sptr self, int ninputs, int noutputs) -> bool"""
        return _rtty_swig.rtty_decode_ff_sptr_check_topology(self, ninputs, noutputs)

    def alias(self):
        r"""alias(rtty_decode_ff_sptr self) -> std::string"""
        return _rtty_swig.rtty_decode_ff_sptr_alias(self)

    def set_block_alias(self, name):
        r"""set_block_alias(rtty_decode_ff_sptr self, std::string name)"""
        return _rtty_swig.rtty_decode_ff_sptr_set_block_alias(self, name)

    def _post(self, which_port, msg):
        r"""_post(rtty_decode_ff_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _rtty_swig.rtty_decode_ff_sptr__post(self, which_port, msg)

    def message_ports_in(self):
        r"""message_ports_in(rtty_decode_ff_sptr self) -> swig_int_ptr"""
        return _rtty_swig.rtty_decode_ff_sptr_message_ports_in(self)

    def message_ports_out(self):
        r"""message_ports_out(rtty_decode_ff_sptr self) -> swig_int_ptr"""
        return _rtty_swig.rtty_decode_ff_sptr_message_ports_out(self)

    def message_subscribers(self, which_port):
        r"""message_subscribers(rtty_decode_ff_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _rtty_swig.rtty_decode_ff_sptr_message_subscribers(self, which_port)

# Register rtty_decode_ff_sptr in _rtty_swig:
_rtty_swig.rtty_decode_ff_sptr_swigregister(rtty_decode_ff_sptr)


rtty_decode_ff_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
rtty_decode_ff = rtty_decode_ff.make;



